name: Joan Daniel Lillo
favicon: null
layout_spectrum: 0.8961151479743421
typography_spectrum: 0.8223580427002162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e6e7e9'
    - '#355a5f'
    - '#49bdc9'
    - '#ee353c'
  brandStrength: 0.375
  lightness: 0.4591640199068934
  saturation: 0.6098755095154047
  rhythmicContrast: 0.9612744487822056
purpose: []
